### ISSUE TITLE
I have another problem. After I converted my HTML file to a PDF file, the PDF file was garbled, and I specified UTF-8 encoding.

### ISSUE THREAD

**Issue by Hzzhang-nlp** [vivifyhealthcare/PDF-Generator-Python#10]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mallajagadeesh** [comment]
@Hzzhang-nlp 
Sure, to generate PDFs, you'll need to install wkhtmltopdf. You can download it from [here](https://wkhtmltopdf.org/downloads.html). Once installed, follow the next steps outlined in the [repository](https://github.com/vivifyhealthcare/PDF-Generator-Python). Let me know if you need any further assistance!
