### ISSUE TITLE
PDF Generator via API Endpoint

### ISSUE THREAD

**Issue by srujithapyla** [vivifyhealthcare/PDF-Generator-Python#2]
### Convert The HTML To PDF By PDF Generator 

Convert The HTML To PDF By PDF Generator in Projects developed on .net core or Node.

**Comment by ghost** [comment]
[https://github.com/vivifyhealthcare/PDF-Generator-Python/releases/tag/PDF-Generator_v1.1.0](https://github.com/vivifyhealthcare/PDF-Generator-Python/releases/tag/PDF-Generator_v1.1.0)
Generate PDF from HTML via Rest API and save the PDF file in configured s3 Bucket
